<?php

namespace Ajax\semantic\html\base\constants\icons;

use Ajax\common\BaseEnum;

abstract class Brands extends BaseEnum {
	const ADN="adn", ANDROID="android", ANGELLIST="angellist", APPLE="apple", BEHANCE="behance", BEHANCE_SQUARE="behance square", BITBUCKET="bitbucket", BITBUCKET_SQUARE="bitbucket square", BITCOIN="bitcoin", BUYSELLADS="buysellads", CODEPEN="codepen", CONNECTDEVELOP="connectdevelop", DASHCUBE="dashcube", DELICIOUS="delicious", DEVIANTART="deviantart", DIGG="digg", DRIBBBLE="dribbble", DROPBOX="dropbox", DRUPAL="drupal", EMPIRE="empire", FACEBOOK="facebook", FACEBOOK_SQUARE="facebook square", FLICKR="flickr", FORUMBEE="forumbee", FOURSQUARE="foursquare", GIT="git", GIT_SQUARE="git square", GITHUB_ALTERNATE="github alternate", GITHUB="github", GITHUB_SQUARE="github square", GITTIP="gittip", GOOGLE="google", GOOGLE_PLUS="google plus", GOOGLE_PLUS_SQUARE="google plus square", HACKER_NEWS="hacker news", INSTAGRAM="instagram", IOXHOST="ioxhost", JOOMLA="joomla", JSFIDDLE="jsfiddle", LASTFM="lastfm", LASTFM_SQUARE="lastfm square", LEANPUB="leanpub", LINKEDIN="linkedin", LINKEDIN_SQUARE="linkedin square", LINUX="linux", MAXCDN="maxcdn", MEANPATH="meanpath", MEDIUM="medium", PAGELINES="pagelines", PIED_PIPER_ALTERNATE="pied piper alternate", PIED_PIPER="pied piper", PINTEREST="pinterest", PINTEREST_SQUARE="pinterest square", QQ="qq", REBEL="rebel", REDDIT="reddit", REDDIT_SQUARE="reddit square", RENREN="renren", SELLSY="sellsy", SHIRTSINBULK="shirtsinbulk", SIMPLYBUILT="simplybuilt", SKYATLAS="skyatlas", SKYPE="skype", SLACK="slack", SLIDESHARE="slideshare", SOUNDCLOUD="soundcloud", SPOTIFY="spotify", STACK_EXCHANGE="stack exchange", STACK_OVERFLOW="stack overflow", STEAM="steam", STEAM_SQUARE="steam square", STUMBLEUPON_CIRCLE="stumbleupon circle", STUMBLEUPON="stumbleupon", TENCENT_WEIBO="tencent weibo", TRELLO="trello", TUMBLR="tumblr", TUMBLR_SQUARE="tumblr square", TWITCH="twitch", TWITTER="twitter", TWITTER_SQUARE="twitter square", VIACOIN="viacoin", VIMEO="vimeo", VINE="vine", VK="vk", WECHAT="wechat", WEIBO="weibo", WHATSAPP="whatsapp", WINDOWS="windows", WORDPRESS="wordpress", XING="xing", XING_SQUARE="xing square", YAHOO="yahoo", YELP="yelp", YOUTUBE="youtube", YOUTUBE_PLAY="youtube play", YOUTUBE_SQUARE="youtube square";
}
